export const ADD_COMMENT = 'ADD_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const TOGGLE_ADD_COMMENT_MODAL_VISIBILITY = 'TOGGLE_ADD_COMMENT_MODAL_VISIBILITY'; // eslint-disable-line
