export const ADD_COMMENT = 'ADD_COMMENT';
export const DELETE_COMMENT = 'DELETE_COMMENT';
export const TOGGLE_ADD_COMMENT_MODAL_VISIBILITY = 'TOGGLE_ADD_COMMENT_MODAL_VISIBILITY'; // eslint-disable-line

export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const FETCH_USER = 'FETCH_USER';
export const SET_USER_AVATAR = 'SET_USER_AVATAR';
export const FETCH_USERS = 'FETCH_USERS';
export const FETCH_USERS_SEEN = 'FETCH_USERS_SEEN';
export const FETCH_COMMENTS = 'FETCH_COMMENTS';
export const FETCH_COMMENT = 'FETCH_COMMENT';
